name: GoTestAndBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'

    - name: Test
      run: go test -v ./backend/...
      
    - name: Build
      run: go build -v ./backend/.


