name: GoTestAndBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code and Go Setup
        uses: actions/checkout@v4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'
          cache: true
          cache-dependency-path: ./backend/go.sum

      - name: Install Dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Run Tests
        working-directory: ./backend
        run: go test -v ./...

      - name: Build
        working-directory: ./backend/src
        run: go build .
