name: GoTestAndBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.6'

      # Run go mod tidy in the backend/ directory
      - name: Install Dependencies
        working-directory: ./backend
        run: go mod tidy

      # Run tests in the backend/ directory
      - name: Run Tests
        working-directory: ./backend
        run: go test -v ./...

      # Build the Go binary from backend/main.go
      - name: Build
        working-directory: ./backend
        run: go build .
